/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package doanpttkhttt.view;

import com.mysql.jdbc.PreparedStatement;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class Banhang extends javax.swing.JPanel {

    /**
     * Creates new form Banhang
     */
    public Banhang() {
        initComponents();
        xuatdanhsach();
             
    }
    public void capnhat(String str){
        JOptionPane.showMessageDialog(this,str);
    }
    public DefaultTableModel xuatdanhsach()
    {
        String header[] = {"mã hóa đơn","Tên người nhập", "Tên người mua ","tổng tiền"};
         DefaultTableModel tblModel = new DefaultTableModel(header, 0);
         Vector data=null;
         
         Connection conn = null;
        Statement st = null;
        java.sql.ResultSet rs = null;
             try {
                 String dbURL = "jdbc:mysql://localhost/doanweb";
                String username = "root";
                String password = "";
                conn = DriverManager.getConnection(dbURL, username, password);
            // crate statement
                 st = conn.createStatement();
            // get data from table 'student'
             rs = st.executeQuery("select * from HOADON");
            
            

            while (rs.next()) {
                 data = new Vector();
  data.add(rs.getString(1));
  data.add(rs.getString(2));
  data.add(rs.getString(3));
  data.add(rs.getString(4));
   tblModel.addRow(data);
//                System.out.println(rs.getString(1)+"\t\t"+rs.getString(2));
            }
            // close connection
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

       jTable1.setModel(tblModel);
        jTable1.setBounds(30, 40, 200, 300);
        return tblModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        viewnhap = new javax.swing.JPanel();
        mahoadon = new javax.swing.JTextField();
        tennguoinhap = new javax.swing.JTextField();
        tenkhachhang = new javax.swing.JTextField();
        ngaynhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewChitiethoadon = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        danhsachhoadon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("BÁN HÀNG");

        ngaynhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaynhapActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã hóa đơn");

        jLabel3.setText("Tên người nhập");

        jLabel4.setText("Tên người mua");

        jLabel5.setText("Ngày nhập hàng");

        jButton1.setText("Tạo hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewChitiethoadonLayout = new javax.swing.GroupLayout(viewChitiethoadon);
        viewChitiethoadon.setLayout(viewChitiethoadonLayout);
        viewChitiethoadonLayout.setHorizontalGroup(
            viewChitiethoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        viewChitiethoadonLayout.setVerticalGroup(
            viewChitiethoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("hoàn thành");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewnhapLayout = new javax.swing.GroupLayout(viewnhap);
        viewnhap.setLayout(viewnhapLayout);
        viewnhapLayout.setHorizontalGroup(
            viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewnhapLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewnhapLayout.createSequentialGroup()
                        .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tenkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(tennguoinhap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mahoadon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaynhap)))
                    .addGroup(viewnhapLayout.createSequentialGroup()
                        .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(viewChitiethoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewnhapLayout.setVerticalGroup(
            viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewnhapLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tennguoinhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(viewChitiethoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lập hóa đơn", viewnhap);

        danhsachhoadon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout danhsachhoadonLayout = new javax.swing.GroupLayout(danhsachhoadon);
        danhsachhoadon.setLayout(danhsachhoadonLayout);
        danhsachhoadonLayout.setHorizontalGroup(
            danhsachhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhsachhoadonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        danhsachhoadonLayout.setVerticalGroup(
            danhsachhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhsachhoadonLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách hóa đơn", danhsachhoadon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ngaynhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaynhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaynhapActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Connection conn = null;
        Statement st = null;
        PreparedStatement ps = null;
        java.sql.ResultSet rs = null;
        Vector data=null;
             try {
                 String dbURL = "jdbc:mysql://localhost/doanweb";
                String username = "root";
                String password = "";   
                conn = DriverManager.getConnection(dbURL, username, password);
                 ps=(PreparedStatement) conn.prepareStatement("INSERT INTO hoadon(MAHOADON,TENNGUOINHAP,TENNGUOIMUA,TONGTIEN) VALUES(?,?,?,0)");
                 ps.setString(1,mahoadon.getText());
                 ps.setString(2,tennguoinhap.getText());
                 ps.setString(3,tenkhachhang.getText());
                 int check=ps.executeUpdate();
                 if(check==1)
                 {
                     JOptionPane.showMessageDialog(this, "Tiến hành nhập chi tiết hóa đơn");
                 }
                 else if(check==0){
                     JOptionPane.showMessageDialog(this,"không the them duoc");
                 }
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();}
        
        viewChitiethoadon.removeAll();
         viewChitiethoadon.setLayout(new BorderLayout());
        JPanel node=new ViewChitiethoadon(mahoadon.getText());
         viewChitiethoadon.add(node);
         viewChitiethoadon.validate();
         viewChitiethoadon.repaint();
         xuatdanhsach();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection conn = null;
        PreparedStatement st = null;
        PreparedStatement ps = null;
        java.sql.ResultSet rs = null;
             try {
                 String dbURL = "jdbc:mysql://localhost/doanweb";
                String usernamedb = "root";
                String password = "";   
                conn =  DriverManager.getConnection(dbURL, usernamedb, password);
              //  them chi tiet hoa don vao hoa don
                                st=(PreparedStatement) conn.prepareStatement("select * from chitiethoadon where MAHD=?");
                st.setString(1,mahoadon.getText());
                rs = st.executeQuery();
                  int tong=0;
                while(rs.next())
                {
                     String gia=rs.getString("GIAHANG");
                     int soluong=rs.getInt("SOLUONG");
                     tong=tong+Integer.parseInt(gia)*soluong;
                }
                st=(PreparedStatement) conn.prepareStatement("UPDATE HOADON set tongtien=? where MAHOADON=?");
                st.setInt(1,tong);
                st.setString(2,mahoadon.getText());
                  st.executeUpdate();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();}
             viewChitiethoadon.removeAll();
             viewChitiethoadon.validate();
             viewChitiethoadon.repaint();
             xuatdanhsach();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel danhsachhoadon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mahoadon;
    private javax.swing.JTextField ngaynhap;
    private javax.swing.JTextField tenkhachhang;
    private javax.swing.JTextField tennguoinhap;
    private javax.swing.JPanel viewChitiethoadon;
    private javax.swing.JPanel viewnhap;
    // End of variables declaration//GEN-END:variables
}
