/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doanpttkhttt.view;

import doanpttkhttt.bean.Danhmucbean;
import doanpttkhttt.control.chuyencontent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class Giaodienchinh extends javax.swing.JFrame {

    /**
     * Creates new form Giaodienchinh
     */
    public Giaodienchinh() {
        initComponents();
        setTitle("Quản lý cửa hàng sách");
        chuyencontent chuyen = new chuyencontent(jpnView);
//        chuyen.setview(jpnBanhang,jlbBanhang);
        chuyen.setview();
        List<Danhmucbean> listitem=new ArrayList<>();
        listitem.add(new Danhmucbean("Banhang",jpnBanhang,jlbBanhang));
          listitem.add(new Danhmucbean("Khohang",jpnKho,jlbKho));
          listitem.add(new Danhmucbean("Nhaphang",jpnNhaphang,jlbNhaphang));
          listitem.add(new Danhmucbean("Doanhthu",jpnDoanhthu,jlbDoanhthu));
          listitem.add(new Danhmucbean("Nhanvien",jpnNhanvien,jlbNhanvien));
          chuyen.setevent(listitem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnBanhang = new javax.swing.JPanel();
        jlbBanhang = new javax.swing.JLabel();
        jpnKho = new javax.swing.JPanel();
        jlbKho = new javax.swing.JLabel();
        jpnNhaphang = new javax.swing.JPanel();
        jlbNhaphang = new javax.swing.JLabel();
        jpnDoanhthu = new javax.swing.JPanel();
        jlbDoanhthu = new javax.swing.JLabel();
        jpnNhanvien = new javax.swing.JPanel();
        jlbNhanvien = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 153));

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-book-50.png"))); // NOI18N
        jLabel1.setText("Quản lí cửa hàng sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jpnBanhang.setBackground(new java.awt.Color(102, 102, 255));
        jpnBanhang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlbBanhang.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlbBanhang.setForeground(new java.awt.Color(255, 255, 102));
        jlbBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-shopping-cart-promotion-30.png"))); // NOI18N
        jlbBanhang.setText("Quản lí bán hàng");

        javax.swing.GroupLayout jpnBanhangLayout = new javax.swing.GroupLayout(jpnBanhang);
        jpnBanhang.setLayout(jpnBanhangLayout);
        jpnBanhangLayout.setHorizontalGroup(
            jpnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBanhangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbBanhang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnBanhangLayout.setVerticalGroup(
            jpnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBanhangLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpnKho.setBackground(new java.awt.Color(102, 102, 255));
        jpnKho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnKho.setPreferredSize(new java.awt.Dimension(208, 90));

        jlbKho.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlbKho.setForeground(new java.awt.Color(255, 255, 102));
        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-warehouse-30.png"))); // NOI18N
        jlbKho.setText("Quản lí kho hàng");

        javax.swing.GroupLayout jpnKhoLayout = new javax.swing.GroupLayout(jpnKho);
        jpnKho.setLayout(jpnKhoLayout);
        jpnKhoLayout.setHorizontalGroup(
            jpnKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbKho, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKhoLayout.setVerticalGroup(
            jpnKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbKho)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnNhaphang.setBackground(new java.awt.Color(102, 102, 255));
        jpnNhaphang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnNhaphang.setPreferredSize(new java.awt.Dimension(208, 90));

        jlbNhaphang.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlbNhaphang.setForeground(new java.awt.Color(255, 255, 102));
        jlbNhaphang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-container-truck-30.png"))); // NOI18N
        jlbNhaphang.setText("Quản lí nhập hàng");

        javax.swing.GroupLayout jpnNhaphangLayout = new javax.swing.GroupLayout(jpnNhaphang);
        jpnNhaphang.setLayout(jpnNhaphangLayout);
        jpnNhaphangLayout.setHorizontalGroup(
            jpnNhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhaphangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbNhaphang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnNhaphangLayout.setVerticalGroup(
            jpnNhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhaphangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbNhaphang)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpnDoanhthu.setBackground(new java.awt.Color(102, 102, 255));
        jpnDoanhthu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnDoanhthu.setPreferredSize(new java.awt.Dimension(208, 90));

        jlbDoanhthu.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlbDoanhthu.setForeground(new java.awt.Color(255, 255, 102));
        jlbDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-statistics-30.png"))); // NOI18N
        jlbDoanhthu.setText("Thống kê doanh thu");

        javax.swing.GroupLayout jpnDoanhthuLayout = new javax.swing.GroupLayout(jpnDoanhthu);
        jpnDoanhthu.setLayout(jpnDoanhthuLayout);
        jpnDoanhthuLayout.setHorizontalGroup(
            jpnDoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhthuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDoanhthu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDoanhthuLayout.setVerticalGroup(
            jpnDoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhthuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbDoanhthu)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnNhanvien.setBackground(new java.awt.Color(102, 102, 255));
        jpnNhanvien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnNhanvien.setPreferredSize(new java.awt.Dimension(208, 90));

        jlbNhanvien.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlbNhanvien.setForeground(new java.awt.Color(255, 255, 102));
        jlbNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanpttkhttt/icon_image/icons8-employee-50.png"))); // NOI18N
        jlbNhanvien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jpnNhanvienLayout = new javax.swing.GroupLayout(jpnNhanvien);
        jpnNhanvien.setLayout(jpnNhanvienLayout);
        jpnNhanvienLayout.setHorizontalGroup(
            jpnNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNhanvien)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpnNhanvienLayout.setVerticalGroup(
            jpnNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanvienLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbNhanvien)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnKho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jpnNhaphang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jpnDoanhthu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jpnNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jpnBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jpnBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jpnKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnNhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnDoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giaodienchinh().setVisible(true);
            }
        });
    }
    public void thungan()
    {
        this.jpnKho.setVisible(false);
        this.jpnDoanhthu.setVisible(false);
        this.jpnNhaphang.setVisible(false);
        this.jpnNhanvien.setVisible(false);
        this.jlbKho.setVisible(false);
    }
    public void thukho()
    {
        this.jpnDoanhthu.setVisible(false);
        this.jpnNhanvien.setVisible(false);     
        this.jpnBanhang.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbBanhang;
    private javax.swing.JLabel jlbDoanhthu;
    private javax.swing.JLabel jlbKho;
    private javax.swing.JLabel jlbNhanvien;
    private javax.swing.JLabel jlbNhaphang;
    private javax.swing.JPanel jpnBanhang;
    private javax.swing.JPanel jpnDoanhthu;
    private javax.swing.JPanel jpnKho;
    private javax.swing.JPanel jpnNhanvien;
    private javax.swing.JPanel jpnNhaphang;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
