/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package doanpttkhttt.view;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ADMIN
 */
public class ViewChitiethoadon extends javax.swing.JPanel {
        Connection conn = null;
        Statement st = null;
        PreparedStatement ps = null;
        java.sql.ResultSet rs = null;
        String dbURL = "jdbc:mysql://localhost/csdl";
        String username = "root";
        String password = ""; 

    public ViewChitiethoadon() {
        initComponents();
    }
    public ViewChitiethoadon(String mahd) {
        initComponents();
        macthd.setText(mahd);
        setsach();
    }
      public void setsach()
    {
         try {
                conn =  DriverManager.getConnection(dbURL, username, password);
                st=(com.mysql.jdbc.Statement) conn.createStatement();
                rs=st.executeQuery("select TENSACH FROM SACH");
               while(rs.next())
               {
                    sachban.addItem(rs.getString("TENSACH"));
               }
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewerCTHD = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        macthd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        soluong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sachban = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(252, 252, 252));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("CHI TIẾT HÓA ĐƠN :");

        macthd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        macthd.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên Sách");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số lượng");

        soluong.setBackground(new java.awt.Color(242, 242, 242));
        soluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soluong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluongActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sachban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout viewerCTHDLayout = new javax.swing.GroupLayout(viewerCTHD);
        viewerCTHD.setLayout(viewerCTHDLayout);
        viewerCTHDLayout.setHorizontalGroup(
            viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewerCTHDLayout.createSequentialGroup()
                .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(viewerCTHDLayout.createSequentialGroup()
                            .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(viewerCTHDLayout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jLabel1))
                                .addGroup(viewerCTHDLayout.createSequentialGroup()
                                    .addGap(174, 174, 174)
                                    .addComponent(macthd)))
                            .addGap(110, 110, 110))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, viewerCTHDLayout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(jLabel2)
                            .addGap(41, 41, 41))
                        .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1))
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sachban, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        viewerCTHDLayout.setVerticalGroup(
            viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewerCTHDLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(macthd)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sachban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerCTHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
             try {  
                conn =  DriverManager.getConnection(dbURL, username, password);
                st=(Statement) conn.createStatement();
                rs=st.executeQuery("select SLTON FROM SACH WHERE TENSACH like'%"+sachban.getSelectedItem().toString()+"%'");
                int ban=0;
                int conlai=0;
                if(st==null){
                ban=0;
                }
                else{
                while(rs.next())
                {
                    ban+=Integer.parseInt(soluong.getText());
                    conlai=rs.getInt("SLTON");
                }
                }
                if(ban!=0){
                //them chi tiet hoa don vao hoa don
                 ps=(PreparedStatement) conn.prepareStatement("INSERT INTO CHITIETHD(MAHD,MASACH,SOLUONG,GIA) VALUES(?,?,?,?)");
                 ps.setString(1,macthd.getText());
                  rs=st.executeQuery("SELECT MASACH FROM SACH WHERE TENSACH like'%"+sachban.getSelectedItem().toString()+"%'");
                 while(rs.next()){
                    ps.setString(2,rs.getString("MASACH"));
                 break;
                 }
                 ps.setInt(3,Integer.parseInt(soluong.getText()));
                 rs=st.executeQuery("SELECT GIA FROM SACH WHERE TENSACH like'%"+sachban.getSelectedItem().toString()+"%'");
                 while(rs.next()){
                    ps.setInt(4,rs.getInt("GIA")+10000);
                 break;
                 }
                 int check=ps.executeUpdate();
                 
                 if(check==1)
                 {
                     int update=conlai-ban;
                 ps=(PreparedStatement) conn.prepareStatement("UPDATE SACH SET SLTON=? WHERE TENSACH like '%"+sachban.getSelectedItem().toString()+"%'");
                 ps.setInt(1,update);
                 ps.executeUpdate();
                     JOptionPane.showMessageDialog(this,"đã nhập chi tiết hóa đơn,nếu muốn dừng lại vui lòng chọn HOÀN THÀNH");
                 }
                 else if(check==0){
                     JOptionPane.showMessageDialog(this,"không the them duoc");
                 }
                }
                else
                    JOptionPane.showMessageDialog(this,"cửa hàng hiện không có sách này");
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Thông tin hóa đơn có lẽ sai hoặc đã bị trùng,vui lòng nhập lại");
            ex.printStackTrace();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soluongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel macthd;
    private javax.swing.JComboBox<String> sachban;
    private javax.swing.JTextField soluong;
    private javax.swing.JPanel viewerCTHD;
    // End of variables declaration//GEN-END:variables
}
