/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package doanpttkhttt.view;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ADMIN
 */
public class ViewChitiethoadon extends javax.swing.JPanel {

    /**
     * Creates new form ViewChitiethoadon
     */
    public ViewChitiethoadon() {
        initComponents();
    }
    public ViewChitiethoadon(String mahd) {
        initComponents();
        macthd.setText(mahd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewerCTHD = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        macthd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tenhang = new javax.swing.JTextField();
        soluong = new javax.swing.JTextField();
        gia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 252, 252));

        jLabel4.setText("CHI TIẾT HÓA ĐƠN :");

        macthd.setText("jLabel5");

        jLabel1.setText("Tên hàng");

        jLabel2.setText("Số lượng");

        jLabel3.setText("Giá tiền");

        tenhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenhangActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewerCTHDLayout = new javax.swing.GroupLayout(viewerCTHD);
        viewerCTHD.setLayout(viewerCTHDLayout);
        viewerCTHDLayout.setHorizontalGroup(
            viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewerCTHDLayout.createSequentialGroup()
                .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel4))
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(macthd))
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewerCTHDLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soluong))
                            .addGroup(viewerCTHDLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gia))
                            .addGroup(viewerCTHDLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(viewerCTHDLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        viewerCTHDLayout.setVerticalGroup(
            viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewerCTHDLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(macthd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewerCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerCTHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenhangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Connection conn = null;
        Statement st = null;
        PreparedStatement ps = null;
        java.sql.ResultSet rs = null;
             try {
                 String dbURL = "jdbc:mysql://localhost/doanweb";
                String usernamedb = "root";
                String password = "";   
                conn =  DriverManager.getConnection(dbURL, usernamedb, password);
                st=(Statement) conn.createStatement();
                rs=st.executeQuery("select SLTON FROM SACH WHERE TENSACH='"+tenhang.getText()+"'");
                int ban=0;
                int conlai=0;
                if(st==null){
                ban=0;
                }
                else{
                while(rs.next())
                {
                    ban+=Integer.parseInt(soluong.getText());
                    conlai=rs.getInt("SLTON");
                }
                }
                if(ban!=0){
                //them chi tiet hoa don vao hoa don
                 ps=(PreparedStatement) conn.prepareStatement("INSERT INTO CHITIETHOADON(MAHD,TENHANG,SOLUONG,GIAHANG) VALUES(?,?,?,?)");
                 ps.setString(1,macthd.getText());
                 ps.setString(2,tenhang.getText());
                 ps.setInt(3,Integer.parseInt(soluong.getText()));
                 int test=Integer.parseInt(gia.getText());
                 ps.setInt(4,test);
                 int check=ps.executeUpdate();
                 
                 if(check==1)
                 {
                     int update=conlai-ban;
                 ps=(PreparedStatement) conn.prepareStatement("UPDATE SACH SET SLTON=? WHERE TENSACH like '%"+tenhang.getText()+"%'");
                 ps.setInt(1,update);
                 ps.executeUpdate();
                     JOptionPane.showMessageDialog(this,"đã nhập chi tiết hóa đơn,nếu muốn dừng lại vui lòng chọn HOÀN THÀNH");
                 }
                 else if(check==0){
                     JOptionPane.showMessageDialog(this,"không the them duoc");
                 }
                }
                else
                    JOptionPane.showMessageDialog(this,"cửa hàng hiện không có sách này");
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel macthd;
    private javax.swing.JTextField soluong;
    private javax.swing.JTextField tenhang;
    private javax.swing.JPanel viewerCTHD;
    // End of variables declaration//GEN-END:variables
}
